server:
  port: "8080"
  shutdown_timeout: 30s

database:
  host: "localhost"
  port: "5433"
  user: "k8s_admin"
  password: "SecureP@ssword123"
  db_name: "backend"

nats:
  url: "nats://localhost:4222"
